language: c
sudo: false

services:
  - redis-server

addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - r-recommended
      - pandoc
      - texinfo
      - texlive
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-math-extra
      - qpdf

env:
  global:
    - RunRRedisTests=yes
    - R_LIBS_USER=~/R/library

cache:
  directories:
    $R_LIBS_USER

before_script:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'install.packages(c("devtools", "covr"), repos="https://cran.rstudio.com", dependencies=TRUE)'

script:
  - Rscript -e 'devtools::check(document=FALSE)'

after_success:
  - Rscript -e 'library(rredis); covr::codecov()'
